apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Deep Insights
    categories: Storage
    console.openshift.io/plugins: '["odf-console"]'
    description: Fusion Data Foundation provides a common control plane for storage
      solutions on IBM Spectrum Fusion.
    operatorframework.io/initialization-resource: |-
      {
        "apiVersion": "odf.openshift.io/v1alpha1",
        "kind": "StorageSystem",
        "metadata": {
          "name": "ocs-storagecluster-storagesystem",
          "namespace": "openshift-storage"
        },
        "spec": {
          "kind": "storagecluster.ocs.openshift.io/v1",
          "name": "ocs-storagecluster",
          "namespace": "openshift-storage"
        }
      }
    operatorframework.io/suggested-namespace: openshift-storage
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    repository: https://github.com/IBM
    support: IBM
    vendors.odf.openshift.io/kind: '["storagecluster.ocs.openshift.io/v1", "flashsystemcluster.odf.ibm.com/v1alpha1"]'
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
  name: fdf-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: StorageSystem is the Schema for the storagesystems API
      displayName: Storage System
      kind: StorageSystem
      name: storagesystems.odf.openshift.io
      resources:
      - kind: FlashSystemCluster
        name: flashsystemclusters.odf.ibm.com
        version: v1alpha1
      - kind: StorageCluster
        name: storageclusters.ocs.openshift.io
        version: v1
      version: v1alpha1
  displayName: Fusion Data Foundation
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - operator
  - data
  - storage
  links:
  - name: Source Code
    url: https://github.com/IBM
  maintainers:
  - email: support@ibm.com
    name: IBM Support
  maturity: alpha
  provider:
    name: IBM
  version: 0.0.0
