---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - odf.openshift.io
  resources:
  - storagesystems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - odf.openshift.io
  resources:
  - storagesystems/finalizers
  verbs:
  - update
- apiGroups:
  - odf.openshift.io
  resources:
  - storagesystems/status
  verbs:
  - get
  - patch
  - update
