apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Deep Insights
    categories: Storage
    console.openshift.io/plugins: '["odf-console"]'
    containerImage: quay.io/ocs-dev/odf-operator:latest
    description: OpenShift Data Foundation provides a common control plane for storage
      solutions on OpenShift Container Platform.
    features.operators.openshift.io/token-auth-aws: "true"
    operatorframework.io/initialization-resource: |-
      {
        "apiVersion": "odf.openshift.io/v1alpha1",
        "kind": "StorageSystem",
        "metadata": {
          "name": "ocs-storagecluster-storagesystem",
          "namespace": "openshift-storage"
        },
        "spec": {
          "kind": "storagecluster.ocs.openshift.io/v1",
          "name": "ocs-storagecluster",
          "namespace": "openshift-storage"
        }
      }
    operatorframework.io/suggested-namespace: openshift-storage
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    operators.openshift.io/valid-subscription: '["OpenShift Platform Plus","OpenShift
      Data Foundation Essentials","OpenShift Data Foundation Advanced"]'
    repository: https://github.com/red-hat-storage/odf-operator
    support: Red Hat
    vendors.odf.openshift.io/kind: '["storagecluster.ocs.openshift.io/v1", "flashsystemcluster.odf.ibm.com/v1alpha1"]'
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
  name: odf-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: StorageSystem is the Schema for the storagesystems API
      displayName: Storage System
      kind: StorageSystem
      name: storagesystems.odf.openshift.io
      resources:
      - kind: FlashSystemCluster
        name: flashsystemclusters.odf.ibm.com
        version: v1alpha1
      - kind: StorageCluster
        name: storageclusters.ocs.openshift.io
        version: v1
      version: v1alpha1
  description: |
    **Red Hat OpenShift Data Foundation** deploys three operators.

    ### OpenShift Data Foundation
    The OpenShift Data Foundation operator is the primary operator for
    OpenShift Data Foundation. It serves to facilitate the other operators in
    OpenShift Data Foundation by performing administrative tasks outside their
    scope as well as watching and configuring their CustomResources.

    ### Rook
    [Rook][1] deploys and manages Ceph on OpenShift, which provides block,
    file and object storage.

    ### NooBaa operator
    The NooBaa operator deploys and manages the [NooBaa][2] Multi-Cloud Gateway
    on OpenShift, which provides object storage.

    # Core Capabilities
    * **Self-managing service:** No matter which supported storage technologies
    you choose, OpenShift Data Foundation ensures that resources can be
    deployed and managed automatically.

    * **Hyper-scale or hyper-converged:** With OpenShift Data Foundation you
    can either build dedicated storage clusters or hyper-converged clusters
    where your apps run alongside storage.

    * **File, Block, and Object provided by OpenShift Data Foundation:**
    OpenShift Data Foundation integrates Ceph with multiple storage
    presentations including object storage (compatible with S3), block storage,
    and POSIX-compliant shared file system.

    * **Your data, protected:** OpenShift Data Foundation efficiently
    distributes and replicates your data across your cluster to minimize the
    risk of data loss. With snapshots, cloning, and versioning, no more losing
    sleep over your data.

    * **Elastic storage in your datacenter:** Scale is now possible in your
    datacenter. Get started with a few terabytes, and easily scale up.

    * **Simplified data management:** Easily create hybrid and multi-cloud data
    storage for your workloads, using a single namespace.

    # Subscriptions
    OpenShift Data Foundation requires a matching 1:1 ratio with the OpenShift
    subscription used. The Essential subscription is included in the OpenShift
    Platform Plus subscription. Disaster Recovery features, external mode, and
    KMS integration for encryption at rest require a bundle of OpenShift
    Platform Plus with OpenShift Data Foundation Advanced subscription.

    [1]: https://rook.io
    [2]: https://www.noobaa.io
  displayName: OpenShift Data Foundation
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - operator
  - data
  - storage
  links:
  - name: Source Code
    url: https://github.com/red-hat-storage/odf-operator
  maintainers:
  - email: ocs-support@redhat.com
    name: Red Hat Support
  maturity: alpha
  minKubeVersion: 1.16.0
  provider:
    name: Red Hat
  version: 0.0.0
