## Append samples you want in your CSV to this file as resources ##
resources:
- odf_v1alpha1_storagesystem.yaml
- odf_v1alpha1_multicloudgateway.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
